[workspace]
resolver = "2"
members = [
    'pokefinder_rs_core',
    'pokefinder_rs_ui',
    'encounter_table_generator'
]

[profile.release]
lto = true
strip = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2