use crate::enums::{Game, ShadowType, Shiny};
use crate::gen3::{LockInfo, ShadowTemplate};
use crate::parents::StaticTemplate;

pub(crate) static STARTERS: [StaticTemplate; 9] = [
    StaticTemplate::new(Game::EMERALD, 152, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::EMERALD, 155, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::EMERALD, 158, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::RSE, 252, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::RSE, 255, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::RSE, 258, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 1, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 4, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 7, 0, Shiny::Random, 255, 255, 0, 5),
];

pub(crate) static FOSSILS: [StaticTemplate; 5] = [
    StaticTemplate::new(Game::RSE, 345, 0, Shiny::Random, 255, 255, 0, 20),
    StaticTemplate::new(Game::RSE, 347, 0, Shiny::Random, 255, 255, 0, 20),
    StaticTemplate::new(Game::FRLG, 138, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 140, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 142, 0, Shiny::Random, 255, 255, 0, 5),
];

pub(crate) static GIFTS: [StaticTemplate; 9] = [
    StaticTemplate::new(Game::RSE, 351, 0, Shiny::Random, 255, 255, 0, 25),
    StaticTemplate::new(Game::RSE, 374, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::RSE, 360, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 106, 0, Shiny::Random, 255, 255, 0, 25),
    StaticTemplate::new(Game::FRLG, 107, 0, Shiny::Random, 255, 255, 0, 25),
    StaticTemplate::new(Game::FRLG, 129, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::FRLG, 131, 0, Shiny::Random, 255, 255, 0, 25),
    StaticTemplate::new(Game::FRLG, 133, 0, Shiny::Random, 255, 255, 0, 25),
    StaticTemplate::new(Game::FRLG, 175, 0, Shiny::Random, 255, 255, 0, 5),
];

pub(crate) static GAME_CORNER: [StaticTemplate; 10] = [
    StaticTemplate::new(Game::FIRE_RED, 63, 0, Shiny::Random, 255, 255, 0, 9),
    StaticTemplate::new(Game::FIRE_RED, 35, 0, Shiny::Random, 255, 255, 0, 8),
    StaticTemplate::new(Game::FIRE_RED, 123, 0, Shiny::Random, 255, 255, 0, 25),
    StaticTemplate::new(Game::FIRE_RED, 147, 0, Shiny::Random, 255, 255, 0, 18),
    StaticTemplate::new(Game::FIRE_RED, 137, 0, Shiny::Random, 255, 255, 0, 26),
    StaticTemplate::new(Game::LEAF_GREEN, 63, 0, Shiny::Random, 255, 255, 0, 7),
    StaticTemplate::new(Game::LEAF_GREEN, 35, 0, Shiny::Random, 255, 255, 0, 12),
    StaticTemplate::new(Game::LEAF_GREEN, 127, 0, Shiny::Random, 255, 255, 0, 18),
    StaticTemplate::new(Game::LEAF_GREEN, 147, 0, Shiny::Random, 255, 255, 0, 24),
    StaticTemplate::new(Game::LEAF_GREEN, 137, 0, Shiny::Random, 255, 255, 0, 18),
];

pub(crate) static STATIONARY: [StaticTemplate; 6] = [
    StaticTemplate::new(Game::RSE, 352, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::RSE, 101, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::EMERALD, 185, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::FRLG, 143, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::FRLG, 101, 0, Shiny::Random, 255, 255, 0, 34),
    StaticTemplate::new(Game::FRLG, 97, 0, Shiny::Random, 255, 255, 0, 30),
];

pub(crate) static LEGENDS: [StaticTemplate; 14] = [
    StaticTemplate::new(Game::RSE, 377, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::RSE, 378, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::RSE, 379, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(
        Game::from_bits_truncate(Game::EMERALD.bits() | Game::RUBY.bits()),
        380,
        0,
        Shiny::Random,
        255,
        255,
        0,
        50,
    ),
    StaticTemplate::new(
        Game::from_bits_truncate(Game::EMERALD.bits() | Game::SAPPHIRE.bits()),
        381,
        0,
        Shiny::Random,
        255,
        255,
        0,
        50,
    ),
    StaticTemplate::new(Game::SAPPHIRE, 382, 0, Shiny::Random, 255, 255, 0, 45),
    StaticTemplate::new(Game::EMERALD, 382, 0, Shiny::Random, 255, 255, 0, 70),
    StaticTemplate::new(Game::RUBY, 383, 0, Shiny::Random, 255, 255, 0, 45),
    StaticTemplate::new(Game::EMERALD, 383, 0, Shiny::Random, 255, 255, 0, 70),
    StaticTemplate::new(Game::RSE, 384, 0, Shiny::Random, 255, 255, 0, 70),
    StaticTemplate::new(Game::FRLG, 144, 0, Shiny::Random, 255, 255, 0, 50),
    StaticTemplate::new(Game::FRLG, 145, 0, Shiny::Random, 255, 255, 0, 50),
    StaticTemplate::new(Game::FRLG, 146, 0, Shiny::Random, 255, 255, 0, 50),
    StaticTemplate::new(Game::FRLG, 150, 0, Shiny::Random, 255, 255, 0, 70),
];

pub(crate) static EVENTS: [StaticTemplate; 6] = [
    StaticTemplate::new(Game::EMERALD, 151, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::EMERALD, 386, 3, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::FIRE_RED, 386, 1, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::LEAF_GREEN, 386, 2, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(
        Game::from_bits_truncate(Game::EMERALD.bits() | Game::FRLG.bits()),
        249,
        0,
        Shiny::Random,
        255,
        255,
        0,
        70,
    ),
    StaticTemplate::new(
        Game::from_bits_truncate(Game::EMERALD.bits() | Game::FRLG.bits()),
        250,
        0,
        Shiny::Random,
        255,
        255,
        0,
        70,
    ),
];

pub(crate) static GALES_COLO: [StaticTemplate; 69] = [
    StaticTemplate::new(Game::COLOSSEUM, 197, 0, Shiny::Never, 255, 255, 0, 26),
    StaticTemplate::new(Game::COLOSSEUM, 196, 0, Shiny::Never, 255, 255, 0, 25),
    StaticTemplate::new(Game::COLOSSEUM, 250, 0, Shiny::Never, 255, 255, 0, 70),
    StaticTemplate::new(Game::COLOSSEUM, 251, 0, Shiny::Never, 255, 255, 0, 10),
    StaticTemplate::new(Game::COLOSSEUM, 25, 0, Shiny::Never, 255, 255, 0, 10),
    StaticTemplate::new(Game::GALES, 133, 0, Shiny::Random, 255, 255, 0, 10),
    StaticTemplate::new(Game::GALES, 152, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::GALES, 155, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::GALES, 158, 0, Shiny::Random, 255, 255, 0, 5),
    StaticTemplate::new(Game::COLOSSEUM, 153, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 156, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 159, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 164, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 180, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 188, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 195, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 200, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 193, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 162, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 218, 0, Shiny::Random, 255, 255, 0, 30),
    StaticTemplate::new(Game::COLOSSEUM, 223, 0, Shiny::Random, 255, 255, 0, 20),
    StaticTemplate::new(Game::COLOSSEUM, 226, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 211, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 307, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 206, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 333, 0, Shiny::Random, 255, 255, 0, 33),
    StaticTemplate::new(Game::COLOSSEUM, 185, 0, Shiny::Random, 255, 255, 0, 35),
    StaticTemplate::new(Game::COLOSSEUM, 237, 0, Shiny::Random, 255, 255, 0, 38),
    StaticTemplate::new(Game::COLOSSEUM, 244, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::COLOSSEUM, 166, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::COLOSSEUM, 245, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::COLOSSEUM, 234, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 221, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 215, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 190, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 205, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 210, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 329, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 168, 0, Shiny::Random, 255, 255, 0, 43),
    StaticTemplate::new(Game::COLOSSEUM, 243, 0, Shiny::Random, 255, 255, 0, 40),
    StaticTemplate::new(Game::COLOSSEUM, 192, 0, Shiny::Random, 255, 255, 0, 45),
    StaticTemplate::new(Game::COLOSSEUM, 225, 0, Shiny::Random, 255, 255, 0, 45),
    StaticTemplate::new(Game::COLOSSEUM, 227, 0, Shiny::Random, 255, 255, 0, 47),
    StaticTemplate::new(Game::COLOSSEUM, 241, 0, Shiny::Random, 255, 255, 0, 48),
    StaticTemplate::new(Game::COLOSSEUM, 359, 0, Shiny::Random, 255, 255, 0, 48),
    StaticTemplate::new(Game::COLOSSEUM, 229, 0, Shiny::Random, 255, 255, 0, 48),
    StaticTemplate::new(Game::COLOSSEUM, 357, 0, Shiny::Random, 255, 255, 0, 49),
    StaticTemplate::new(Game::COLOSSEUM, 376, 0, Shiny::Random, 255, 255, 0, 50),
    StaticTemplate::new(Game::COLOSSEUM, 248, 0, Shiny::Random, 255, 255, 0, 55),
    StaticTemplate::new(Game::COLOSSEUM, 235, 0, Shiny::Random, 255, 255, 0, 45),
    StaticTemplate::new(Game::COLOSSEUM, 213, 0, Shiny::Random, 255, 255, 0, 45),
    StaticTemplate::new(Game::COLOSSEUM, 176, 0, Shiny::Random, 255, 255, 0, 20),
    StaticTemplate::new(Game::GALES, 216, 0, Shiny::Never, 255, 255, 0, 11),
    StaticTemplate::new(Game::GALES, 343, 0, Shiny::Never, 255, 255, 0, 17),
    StaticTemplate::new(Game::GALES, 179, 0, Shiny::Never, 255, 255, 0, 17),
    StaticTemplate::new(Game::GALES, 318, 0, Shiny::Never, 255, 255, 0, 15),
    StaticTemplate::new(Game::GALES, 228, 0, Shiny::Never, 255, 255, 0, 17),
    StaticTemplate::new(Game::GALES, 335, 0, Shiny::Never, 255, 255, 0, 28),
    StaticTemplate::new(Game::GALES, 175, 0, Shiny::Never, 255, 255, 0, 25),
    StaticTemplate::new(Game::GALES, 90, 0, Shiny::Never, 255, 255, 0, 29),
    StaticTemplate::new(Game::GALES, 15, 0, Shiny::Never, 255, 255, 0, 30),
    StaticTemplate::new(Game::GALES, 277, 0, Shiny::Never, 255, 255, 0, 43),
    StaticTemplate::new(Game::GALES, 249, 0, Shiny::Never, 255, 255, 0, 50),
    StaticTemplate::new(Game::GALES, 112, 0, Shiny::Never, 255, 255, 0, 46),
    StaticTemplate::new(Game::GALES, 146, 0, Shiny::Never, 255, 255, 0, 50),
    StaticTemplate::new(Game::GALES, 103, 0, Shiny::Never, 255, 255, 0, 46),
    StaticTemplate::new(Game::GALES, 128, 0, Shiny::Never, 255, 255, 0, 46),
    StaticTemplate::new(Game::GALES, 144, 0, Shiny::Never, 255, 255, 0, 50),
    StaticTemplate::new(Game::GALES, 145, 0, Shiny::Never, 255, 255, 0, 50),
];

pub(crate) static GALES_COLO_SHADOW: [ShadowTemplate; 77] = [
    ShadowTemplate::new(
        Game::COLOSSEUM,
        296,
        Shiny::Random,
        30,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        207,
        Shiny::Random,
        43,
        [
            LockInfo::new(12, 0, 127),
            LockInfo::new(6, 1, 191),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        198,
        Shiny::Random,
        43,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        214,
        Shiny::Random,
        45,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        217,
        Shiny::Random,
        45,
        [
            LockInfo::new(20, 1, 63),
            LockInfo::new(16, 0, 31),
            LockInfo::new(21, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        175,
        Shiny::Random,
        20,
        [
            LockInfo::new(23, 0, 127),
            LockInfo::new(8, 0, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::new(22, 1, 31),
            LockInfo::default(),
        ],
        4,
        ShadowType::EReader,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        179,
        Shiny::Random,
        37,
        [
            LockInfo::new(4, 1, 191),
            LockInfo::new(10, 1, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(16, 1, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::EReader,
    ),
    ShadowTemplate::new(
        Game::COLOSSEUM,
        212,
        Shiny::Random,
        50,
        [
            LockInfo::new(13, 1, 191),
            LockInfo::new(2, 2, 255),
            LockInfo::new(3, 0, 127),
            LockInfo::new(11, 0, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::EReader,
    ),
    ShadowTemplate::new(
        Game::GALES,
        165,
        Shiny::Never,
        10,
        [
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        1,
        ShadowType::SingleLock,
    ),
    ShadowTemplate::new(
        Game::GALES,
        261,
        Shiny::Never,
        10,
        [
            LockInfo::new(12, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        1,
        ShadowType::SingleLock,
    ),
    ShadowTemplate::new(
        Game::GALES,
        363,
        Shiny::Never,
        17,
        [
            LockInfo::new(24, 0, 63),
            LockInfo::new(12, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        363,
        Shiny::Never,
        17,
        [
            LockInfo::new(24, 0, 63),
            LockInfo::new(12, 1, 127),
            LockInfo::new(0, 2, 255),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        316,
        Shiny::Never,
        17,
        [
            LockInfo::new(12, 1, 127),
            LockInfo::new(6, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        273,
        Shiny::Never,
        17,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(24, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::new(0, 0, 127),
            LockInfo::new(12, 0, 127),
        ],
        5,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        273,
        Shiny::Never,
        17,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(24, 1, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(6, 0, 127),
        ],
        5,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        273,
        Shiny::Never,
        17,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(24, 1, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(0, 0, 127),
            LockInfo::new(12, 0, 127),
        ],
        5,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        167,
        Shiny::Never,
        14,
        [
            LockInfo::new(12, 1, 127),
            LockInfo::new(6, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        322,
        Shiny::Never,
        14,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(0, 2, 255),
            LockInfo::new(24, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        285,
        Shiny::Never,
        14,
        [
            LockInfo::new(24, 1, 191),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        301,
        Shiny::Never,
        18,
        [
            LockInfo::new(6, 1, 191),
            LockInfo::new(0, 0, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        100,
        Shiny::Never,
        19,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        296,
        Shiny::Never,
        18,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        37,
        Shiny::Never,
        18,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        355,
        Shiny::Never,
        19,
        [
            LockInfo::new(12, 0, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        280,
        Shiny::Never,
        20,
        [
            LockInfo::new(0, 0, 63),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        303,
        Shiny::Never,
        22,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        361,
        Shiny::Never,
        20,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        1,
        ShadowType::SingleLock,
    ),
    ShadowTemplate::new(
        Game::GALES,
        361,
        Shiny::Never,
        20,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        1,
        ShadowType::SingleLock,
    ),
    ShadowTemplate::new(
        Game::GALES,
        177,
        Shiny::Never,
        22,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        177,
        Shiny::Never,
        22,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        52,
        Shiny::Never,
        22,
        [
            LockInfo::new(6, 0, 63),
            LockInfo::new(0, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        220,
        Shiny::Never,
        22,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::new(0, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        21,
        Shiny::Never,
        22,
        [
            LockInfo::new(18, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        88,
        Shiny::Never,
        23,
        [
            LockInfo::new(12, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        86,
        Shiny::Never,
        23,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        337,
        Shiny::Never,
        25,
        [
            LockInfo::new(0, 1, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        299,
        Shiny::Never,
        26,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        46,
        Shiny::Never,
        28,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        58,
        Shiny::Never,
        28,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        17,
        Shiny::Never,
        30,
        [
            LockInfo::new(0, 0, 0),
            LockInfo::new(12, 0, 127),
            LockInfo::new(18, 0, 31),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        114,
        Shiny::Never,
        30,
        [
            LockInfo::new(12, 1, 191),
            LockInfo::new(6, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        12,
        Shiny::Never,
        30,
        [
            LockInfo::new(12, 1, 191),
            LockInfo::new(6, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        82,
        Shiny::Never,
        30,
        [
            LockInfo::new(18, 2, 255),
            LockInfo::new(0, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        49,
        Shiny::Never,
        32,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::new(24, 0, 0),
            LockInfo::new(12, 0, 63),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        70,
        Shiny::Never,
        32,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::new(24, 0, 0),
            LockInfo::new(12, 0, 63),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        24,
        Shiny::Never,
        33,
        [
            LockInfo::new(6, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        57,
        Shiny::Never,
        34,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        97,
        Shiny::Never,
        34,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::new(0, 0, 0),
        ],
        5,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        55,
        Shiny::Never,
        33,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        302,
        Shiny::Never,
        33,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        85,
        Shiny::Never,
        34,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        1,
        ShadowType::SingleLock,
    ),
    ShadowTemplate::new(
        Game::GALES,
        20,
        Shiny::Never,
        34,
        [
            LockInfo::new(18, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::new(18, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        83,
        Shiny::Never,
        36,
        [
            LockInfo::new(12, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        334,
        Shiny::Never,
        36,
        [
            LockInfo::new(12, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        115,
        Shiny::Never,
        35,
        [
            LockInfo::new(0, 0, 0),
            LockInfo::new(18, 1, 127),
            LockInfo::new(12, 2, 255),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        354,
        Shiny::Never,
        37,
        [
            LockInfo::new(0, 2, 255),
            LockInfo::new(18, 1, 127),
            LockInfo::new(12, 2, 255),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        126,
        Shiny::Never,
        36,
        [
            LockInfo::new(18, 0, 127),
            LockInfo::new(18, 0, 191),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        127,
        Shiny::Never,
        35,
        [
            LockInfo::new(18, 0, 127),
            LockInfo::new(18, 0, 191),
            LockInfo::new(0, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        78,
        Shiny::Never,
        40,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        219,
        Shiny::Never,
        38,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
        ],
        4,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        107,
        Shiny::Never,
        38,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        106,
        Shiny::Never,
        38,
        [
            LockInfo::new(18, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(6, 2, 255),
            LockInfo::new(24, 1, 63),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        108,
        Shiny::Never,
        38,
        [
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 2, 255),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        123,
        Shiny::Never,
        40,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        113,
        Shiny::Never,
        39,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        338,
        Shiny::Never,
        41,
        [
            LockInfo::new(24, 2, 255),
            LockInfo::new(6, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
        ],
        3,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        121,
        Shiny::Never,
        41,
        [
            LockInfo::new(24, 2, 255),
            LockInfo::new(6, 0, 127),
            LockInfo::new(0, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::new(18, 0, 127),
        ],
        5,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        125,
        Shiny::Never,
        43,
        [
            LockInfo::new(0, 0, 0),
            LockInfo::new(24, 0, 63),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        143,
        Shiny::Never,
        43,
        [
            LockInfo::new(0, 0, 0),
            LockInfo::new(24, 0, 63),
            LockInfo::new(6, 1, 127),
            LockInfo::new(18, 1, 127),
            LockInfo::new(0, 0, 0),
        ],
        5,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        62,
        Shiny::Never,
        42,
        [
            LockInfo::new(18, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        122,
        Shiny::Never,
        42,
        [
            LockInfo::new(18, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(24, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(0, 0, 0),
        ],
        5,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        51,
        Shiny::Never,
        40,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(6, 1, 127),
            LockInfo::new(12, 0, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        310,
        Shiny::Never,
        44,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        1,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        373,
        Shiny::Never,
        50,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::default(),
            LockInfo::default(),
            LockInfo::default(),
        ],
        2,
        ShadowType::Salamence,
    ),
    ShadowTemplate::new(
        Game::GALES,
        105,
        Shiny::Never,
        44,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::new(0, 0, 0),
            LockInfo::new(24, 0, 127),
            LockInfo::default(),
        ],
        4,
        ShadowType::FirstShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        131,
        Shiny::Never,
        44,
        [
            LockInfo::new(6, 1, 127),
            LockInfo::new(0, 0, 0),
            LockInfo::new(0, 0, 0),
            LockInfo::new(24, 0, 127),
            LockInfo::new(0, 0, 0),
        ],
        5,
        ShadowType::SecondShadow,
    ),
    ShadowTemplate::new(
        Game::GALES,
        149,
        Shiny::Never,
        55,
        [
            LockInfo::new(0, 0, 127),
            LockInfo::new(18, 0, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(12, 1, 127),
            LockInfo::new(0, 0, 127),
        ],
        5,
        ShadowType::FirstShadow,
    ),
];

pub(crate) static CHANNEL: [StaticTemplate; 1] = [StaticTemplate::new(
    Game::GC,
    385,
    0,
    Shiny::Random,
    255,
    255,
    0,
    5,
)];

pub(crate) static EMERALD: &[u8] = include_bytes!("emerald.bin");

pub(crate) static FIRERED: &[u8] = include_bytes!("firered.bin");

pub(crate) static LEAFGREEN: &[u8] = include_bytes!("leafgreen.bin");

pub(crate) static RUBY: &[u8] = include_bytes!("ruby.bin");

pub(crate) static SAPPHIRE: &[u8] = include_bytes!("sapphire.bin");

pub(crate) static XD: &[u8] = include_bytes!("xd.bin");
